feat: replace NaN values in move commands by 0
NAMeC-team/CRAbE pull request #73
Opened 2023-09-02 17:21 UTC by Wanchai290

Re-implemented from RoboCup 2023, required to not make GrSim explode

2023-09-06 10:23 UTC, benjaminchew4 approved these changes
LGTM

2023-10-11 12:01 UTC, EtienneSchmitz requested changes
Need to issue a warning or an error. 
The presence of 'NaN' (Not a Number) values transmitted on the output is problematic, necessitating user notification and response.

2023-10-11 13:38 UTC, Wanchai290 commented
would a simple `warn!()` do it ? maybe we could have a CLI argument that enforces no NaN values when running tests. what do you think ?

2023-10-15 10:36 UTC, EtienneSchmitz approved these changes

2023-10-15 10:37 UTC, EtienneSchmitz commented
I've enhanced the warning message.

2023-10-19 12:30 UTC, merged