reimpl: ability to clear actions of ActionWrapper for all robots
NAMeC-team/CRAbE pull request #77
Opened 2023-10-14 16:58 UTC by Wanchai290

Feature to re-implement, that was already committed in #75

2023-10-15 10:21 UTC, EtienneSchmitz requested changes
The current function name conflicts with `clean`, causing confusion due to a single-letter difference, which leads to two possible solutions:

1. Rename the function to `clean_all`.
2. Rename 'clean' to 'clear' and 'clear' to `clear_all`.

In my opinion, `clean` is problematic, and `clear` is a better choice because it aligns with the sequential `clear` function.

2023-10-15 12:07 UTC, Wanchai290 commented
lol agreed, I'll do that asap

2023-10-25 12:52 UTC, EtienneSchmitz approved these changes

2023-10-25 14:06 UTC, benjaminchew4 approved these changes

2023-10-25 15:18 UTC, merged